--- 
- name: Update apt package cache
  apt: update_cache=yes
  
- name: Upgrade system
  apt: upgrade=full

- name: Install basic packages
  apt: name="{{item}}" state=present
  with_items:
    - openssh-server
    - git
    - sudo
    - ansible
