---
- when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  import_tasks: apt.yml

- when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  import_tasks: rpm.yml

- when: ansible_distribution == 'Alpine'
  import_tasks: apk.yml
  
- name: Sync configuration
  copy: force=yes backup=no src=torrc dest=/etc/tor/torrc

- name: Start tor service
  service: name=tor state=started

- name: Display hidden service name
  debug: "Node address: {{ lookup('file', '/var/lib/tor/hidden_service/hostname') }}"
