---
- name: Update apt package cache
  apt: update_cache=yes

- name: Upgrade system
  apt: upgrade=full

- name: Install Tor router
  apt: name=tor state=present

- name: Sync configuration
  copy: force=yes backup=no src=torrc dest=/etc/tor/torrc

- name: Start tor service
  service: name=tor state=started

- name: Display hidden service name
  debug: "Node address: {{ lookup('file', '/var/lib/tor/hidden_service/hostname') }}"
