--- 
- name: Upgrade system
  yum: name="*" state=latest

- name: Add epel repository
  yum: name="epel-release" state=latest

- name: Install basic packages
  yum: name="{{item}}" state=latest update_cache=yes
  with_items:
    - openssh-server
    - git
    - sudo
